#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo "🔍 Running type check..."
npm run type-check || exit 1

echo "🧹 Running lint..."
npm run lint || exit 1

echo "🧪 Running tests..."
CI=true npm run test:ci || exit 1

echo "✅ All checks passed!"
